import type { Metadata } from "next";
import { Quicksand } from "next/font/google";

import "./globals.css";


const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PixHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="pt-BR">
        <body className={quicksand.className}>{children}</body>
      </html>
    
  );
}
